### ISSUE TITLE
"The Supervisor Returned an Unexpected Response" for larger snapshots on 32 bit arm platforms (eg raspberry pi's)

### ISSUE THREAD

**Issue by valerix85** [sabeechen/hassio-google-drive-backup#226]
Hi,
form the latest update of HA (0.114.0) seems that the addon is not working.
I've already tried full restart and physical restart, nothing works like before with Hassio Google Drive Backup.
To avoid problems, I've already done the re-authentication with Google...

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.1`
 Home Assistant Version: `0.114.1`
 Supervisor Version: `234`
 Architecture: `armv7`
 Date: `2020-08-16T11:33:38.183750+00:00`
 Timezone: `Europe/Rome`
 Failure Time: `2020-08-16T11:32:41.752325+00:00`
 Last Good Sync: `2020-08-16T11:32:41.159116+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:148 (save)
  addon/backup/drive/driverequests.py:244 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-08-16T00:58:14Z",
        "size": "8.7 GB"
    },
    "GoogleDrive": {
        "snapshots": 1,
        "retained": 0,
        "deletable": 1,
        "name": "GoogleDrive",
        "latest": "2020-08-15T00:53:45Z",
        "size": "2.2 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 1,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_NAME": "REDACTED",
    "Setting.SNAPSHOT_TIME_OF_DAY": "02:01"
}
 ```
 ###### Addon Logs:
 ```
 08-16 13:24:32 INFO [backup.model.coordinator] Syncing Snapshots
08-16 13:24:32 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-16 13:24:32 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/16qmeXtaTELJXzYj1Hbb0st1KU7Qqj31c/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-16 13:24:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2716qmeXtaTELJXzYj1Hbb0st1KU7Qqj31c%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-16 13:24:33 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 16-08-2020 02:58:13' to Google Drive
08-16 13:24:33 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-16 13:24:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AAANsUkqOGeX4hyb7I84vlBf1QcMdNTc0WhaNf2OMnEBdmSngJ21mr46h-QBwjpjzwdbCNxnRYpV8M5Kzsxo-yXJMSdMAPzGbA
08-16 13:24:33 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2352496640
08-16 13:24:33 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-16 13:24:33 INFO [backup.model.coordinator] I'll try again in 5(ish) minutes
08-16 13:29:40 INFO [backup.model.coordinator] Syncing Snapshots
08-16 13:29:40 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-16 13:29:40 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/16qmeXtaTELJXzYj1Hbb0st1KU7Qqj31c/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-16 13:29:40 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2716qmeXtaTELJXzYj1Hbb0st1KU7Qqj31c%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-16 13:29:40 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 16-08-2020 02:58:13' to Google Drive
08-16 13:29:40 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-16 13:29:40 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AAANsUkqOGeX4hyb7I84vlBf1QcMdNTc0WhaNf2OMnEBdmSngJ21mr46h-QBwjpjzwdbCNxnRYpV8M5Kzsxo-yXJMSdMAPzGbA
08-16 13:29:40 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2352496640
08-16 13:29:40 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-16 13:29:40 INFO [backup.model.coordinator] I'll try again in 10(ish) minutes
08-16 13:32:41 INFO [backup.model.coordinator] Syncing Snapshots
08-16 13:32:41 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-16 13:32:41 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/16qmeXtaTELJXzYj1Hbb0st1KU7Qqj31c/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-16 13:32:41 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2716qmeXtaTELJXzYj1Hbb0st1KU7Qqj31c%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-16 13:32:41 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 16-08-2020 02:58:13' to Google Drive
08-16 13:32:41 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-16 13:32:41 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AAANsUkqOGeX4hyb7I84vlBf1QcMdNTc0WhaNf2OMnEBdmSngJ21mr46h-QBwjpjzwdbCNxnRYpV8M5Kzsxo-yXJMSdMAPzGbA
08-16 13:32:41 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2352496640
08-16 13:32:41 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-16 13:32:41 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
 ```
 ###### Supervisor Logs:
 ```
 [32m20-08-16 11:19:45 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m20-08-16 11:19:45 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m20-08-16 11:19:45 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m20-08-16 11:19:45 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m20-08-16 11:19:45 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m20-08-16 11:19:45 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m20-08-16 11:19:45 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m20-08-16 11:19:45 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m20-08-16 11:19:48 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:19:50 INFO (MainThread) [supervisor.api.security] /snapshots/845f6036/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:19:50 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 845f6036[0m
[32m20-08-16 11:20:30 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:20:31 INFO (MainThread) [supervisor.api.security] /snapshots/845f6036/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:20:31 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 845f6036[0m
[32m20-08-16 11:21:51 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:21:52 INFO (MainThread) [supervisor.api.security] /snapshots/845f6036/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:21:52 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 845f6036[0m
[32m20-08-16 11:24:32 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:24:33 INFO (MainThread) [supervisor.api.security] /snapshots/845f6036/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:24:33 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 845f6036[0m
[32m20-08-16 11:29:40 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:29:40 INFO (MainThread) [supervisor.api.security] /snapshots/845f6036/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:29:40 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 845f6036[0m
[32m20-08-16 11:29:54 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:29:54 INFO (MainThread) [supervisor.api.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:32:41 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:32:41 INFO (MainThread) [supervisor.api.security] /snapshots/845f6036/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-16 11:32:41 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 845f6036[0m
[32m20-08-16 11:33:38 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 2020-08-16 13:29:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.camera is taking over 10 seconds
2020-08-16 13:29:50 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:29:50 WARNING (SyncWorker_58) [homeassistant.components.tplink.light] Could not read data for 10.0.0.15: Communication error
2020-08-16 13:29:54 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 80 seconds
2020-08-16 13:30:00 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:30:05 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:30:05 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.camera is taking over 10 seconds
2020-08-16 13:30:15 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:30:20 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-08-16 13:30:25 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:30:35 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:30:45 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:30:50 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-08-16 13:30:51 WARNING (SyncWorker_63) [homeassistant.components.mitemp_bt.sensor] Polling error 
2020-08-16 13:30:51 WARNING (SyncWorker_53) [homeassistant.components.mitemp_bt.sensor] Polling error Could not read data from Mi Temp sensor 58:2D:34:31:2E:C7
2020-08-16 13:30:55 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:31:01 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.primo_piano_temp_battery is taking over 10 seconds
2020-08-16 13:31:05 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:31:15 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:31:20 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-08-16 13:31:24 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 80 seconds
2020-08-16 13:31:25 WARNING (MainThread) [homeassistant.components.light] Updating tplink light took longer than the scheduled update interval 0:00:05
2020-08-16 13:31:50 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-08-16 13:32:20 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-08-16 13:32:25 WARNING (MainThread) [frontend.js.latest.202008110] Icon mdi:file-document-box-outline was renamed to mdi:text-box-outline, please change your config, it will be removed in version 0.115.
2020-08-16 13:32:50 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-08-16 13:32:52 WARNING (SyncWorker_51) [homeassistant.components.mitemp_bt.sensor] Polling error 
2020-08-16 13:32:54 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 80 seconds
2020-08-16 13:33:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.piano_terra_temp_temperature is taking over 10 seconds

 ```

**Comment by Game2Freak** [comment]
I’m having the same issue:

`
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.1`
 Home Assistant Version: `0.114.1`
 Supervisor Version: `234`
 Architecture: `armv7`
 Date: `2020-08-17T09:22:05.556361+00:00`
 Timezone: `Europe/London`
 Failure Time: `2020-08-17T09:21:57.985187+00:00`
 Last Good Sync: `2020-08-17T09:21:57.304827+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:148 (save)
  addon/backup/drive/driverequests.py:244 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-08-17T00:31:17Z",
        "size": "9.9 GB"
    },
    "GoogleDrive": {
        "snapshots": 3,
        "retained": 0,
        "deletable": 3,
        "name": "GoogleDrive",
        "latest": "2020-08-14T00:27:39Z",
        "size": "7.4 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 3,
    "Setting.SNAPSHOT_TIME_OF_DAY": "01:00",
    "Setting.BACKGROUND_COLOR": "#b3b3bd",
    "Setting.ACCENT_COLOR": "#2c2c2e"
}
 ```
 ###### Addon Logs:
 ```
 08-17 09:13:59 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1PuvYep9TK068tQkq81S9hnr1TgDPEpI9/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-17 09:13:59 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271PuvYep9TK068tQkq81S9hnr1TgDPEpI9%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-17 09:13:59 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-08-17 01:31:16' to Google Drive
08-17 09:13:59 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-17 09:13:59 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AAANsUkXcZjRxUaMDl9pZ9dvHv4KNM_wvezjzeLfeR779gEYZ75tea14VxYVu29uw11vKJKId5YT2VB0WtvXbgw4Vcw
08-17 09:13:59 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2649610240
08-17 09:13:59 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-17 09:13:59 INFO [backup.model.coordinator] I'll try again in an hour
08-17 10:13:59 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-17 10:13:59 INFO [backup.model.coordinator] Syncing Snapshots
08-17 10:13:59 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-17 10:13:59 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-17 10:13:59 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1PuvYep9TK068tQkq81S9hnr1TgDPEpI9/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-17 10:14:00 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271PuvYep9TK068tQkq81S9hnr1TgDPEpI9%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-17 10:14:00 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-08-17 01:31:16' to Google Drive
08-17 10:14:00 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-17 10:14:00 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AAANsUkXcZjRxUaMDl9pZ9dvHv4KNM_wvezjzeLfeR779gEYZ75tea14VxYVu29uw11vKJKId5YT2VB0WtvXbgw4Vcw
08-17 10:14:00 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2649610240
08-17 10:14:00 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-17 10:14:00 INFO [backup.model.coordinator] I'll try again in an hour
08-17 10:21:57 INFO [backup.model.coordinator] Syncing Snapshots
08-17 10:21:57 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-17 10:21:57 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1PuvYep9TK068tQkq81S9hnr1TgDPEpI9/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-17 10:21:57 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271PuvYep9TK068tQkq81S9hnr1TgDPEpI9%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-17 10:21:57 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-08-17 01:31:16' to Google Drive
08-17 10:21:57 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-17 10:21:57 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AAANsUkXcZjRxUaMDl9pZ9dvHv4KNM_wvezjzeLfeR779gEYZ75tea14VxYVu29uw11vKJKId5YT2VB0WtvXbgw4Vcw
08-17 10:21:57 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2649610240
08-17 10:21:57 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-17 10:21:57 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-08-17 07:31:43 INFO (MainThread) [supervisor.host.network] Update local network DNS information[0m
[32m20-08-17 07:31:43 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager[0m
[32m20-08-17 07:31:43 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information[0m
[32m20-08-17 07:51:42 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json[0m
[32m20-08-17 08:00:20 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token[0m
[32m20-08-17 08:13:58 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-17 08:13:59 INFO (MainThread) [supervisor.api.security] /snapshots/f9e442f6/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-17 08:13:59 INFO (MainThread) [supervisor.api.snapshots] Download snapshot f9e442f6[0m
[32m20-08-17 08:30:29 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token[0m
[32m20-08-17 08:51:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository[0m
[32m20-08-17 08:51:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/samccauley/hassio-repository repository[0m
[32m20-08-17 08:51:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/marthoc/hassio-addons repository[0m
[32m20-08-17 08:51:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons-example repository[0m
[32m20-08-17 08:51:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m20-08-17 08:51:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/leoMehlig/hassio-onedrive-sync repository[0m
[32m20-08-17 08:51:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[31m20-08-17 08:51:44 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/3e36584a/repository.json: [Errno 2] No such file or directory: '/data/addons/git/3e36584a/repository.json'[0m
[33m20-08-17 08:51:44 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/3e36584a/repository.json[0m
[33m20-08-17 08:51:44 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/c2eea46b/sync/config.json: required key not provided @ data['arch']. Got None[0m
[33m20-08-17 08:51:44 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/c2eea46b/coffee_maker/config.json: required key not provided @ data['arch']. Got None[0m
[32m20-08-17 08:51:44 INFO (MainThread) [supervisor.store] Load add-ons from store: 70 all - 0 new - 0 remove[0m
[32m20-08-17 09:00:39 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token[0m
[32m20-08-17 09:13:59 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-17 09:14:00 INFO (MainThread) [supervisor.api.security] /snapshots/f9e442f6/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-17 09:14:00 INFO (MainThread) [supervisor.api.snapshots] Download snapshot f9e442f6[0m
[32m20-08-17 09:21:57 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-17 09:21:57 INFO (MainThread) [supervisor.api.security] /snapshots/f9e442f6/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-17 09:21:57 INFO (MainThread) [supervisor.api.snapshots] Download snapshot f9e442f6[0m
[32m20-08-17 09:22:05 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 2020-08-17 10:18:31 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   554    0   554    0     0  13850      0 --:--:-- --:--:-- --:--:-- 14205
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   554    0   554    0     0  69250      0 --:--:-- --:--:-- --:--:-- 79142
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   554    0   554    0     0  69250      0 --:--:-- --:--:-- --:--:-- 79142
2020-08-17 10:19:54 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-08-17 10:19:54 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   554    0   554    0     0  42615      0 --:--:-- --:--:-- --:--:-- 46166
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   554    0   554    0     0  50363      0 --:--:-- --:--:-- --:--:-- 50363
2020-08-17 10:21:17 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-08-17 10:21:17 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   554    0   554    0     0  69250      0 --:--:-- --:--:-- --:--:-- 79142
2020-08-17 10:21:25 WARNING (MainThread) [homeassistant.components.remote] Setup of remote platform harmony is taking over 10 seconds.
2020-08-17 10:21:48 ERROR (MainThread) [aioharmony.harmonyclient] 192.168.1.21: Unable to determine if XMPP is enabled: [Errno 110] Connect call failed ('192.168.1.21', 5222)
2020-08-17 10:21:48 WARNING (MainThread) [homeassistant.components.remote] Platform harmony not ready yet. Retrying in 180 seconds.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   554    0   554    0     0  69250      0 --:--:-- --:--:-- --:--:-- 79142

 ```
  `

**Comment by davidsat** [comment]
Hi, Same issue here. Started on upgrade to 0.114 from 0.113.

**Comment by sabeechen** [comment]
I haven't been able to reproduce this on my machines, but I can see a lot of error reports coming in for it.  The nature of the error makes it difficult to diagnose., I might have to release a new version that just provides extra debugging info to make progress on figuring out whats happening.

Hopefully its something more simple.  From the the Home assistant UI, could you try going to Supervisor -> Snapshots and clicking the refresh icon in the top right?  Then sync again and see if the error comes back.  If this works, something is getting messed up in the supervisor's snapshot cache.

Both the error reports coming in look like they're running this on a raspberry pi, so I suspect this may only be an issue on the PI.  Is anyone seeing this that isn't running on a pi?

**Comment by davidsat** [comment]
Hi,
I'm running on a Pi4. Refreshing did not help, although it did present the snapshots in the supervisor->snapshots view where there were none before.

**Comment by Game2Freak** [comment]
I’m on a raspberry pi 3.

Tried the refresh but still receive the same error.

**Comment by sabeechen** [comment]
Looks like its probably only a problem on the PI, which is at least strange.

Again if someone is seeing this error and they aren't running HA on a PI, please chime in so I don't spend too much time investigating down the wrong path.

I've got a pi3 I can dig out of storage to see If I can reproduce this on that hardware.

**Comment by sabeechen** [comment]
I can also see in automatic error reports that only people on the armv7 platform (which is usually only the various raspberrypi's) are reporting this error.  Its only 3 or so reports, but given that the user base of this addon skews heavily toward those x86 (eg running in a VM or on top of ubuntu) I'm feeling pretty confident that this is a problem that only shows up on a raspberry pi.

**Comment by valerix85** [comment]
> I can also see in automatic error reports that only people on the armv7 platform (which is usually only the various raspberrypi's) are reporting this error. Its only 3 or so reports, but given that the user base of this addon skews heavily toward those x86 (eg running in a VM or on top of ubuntu) I'm feeling pretty confident that this is a problem that only shows up on a raspberry pi.

so in this case is an hardware problem of the raspberry pi 4? Just to know if I have to trash it or not...

Thanks

**Comment by sabeechen** [comment]
I'm not sure yet, but probably not.  I'm just trying to narrow down what the cause it so I can figure out what the problem is exactly, reproduce it, and fix it.  My leading theories are:

1. A rouge addon that interferes with my addon
2. A bug in how the addon talks to the supervisor.
3. A bug in the supervisor only on arm platforms (eg rpi's)
 
Hopefully its not (1) because I'd have a lot of trouble narrowing that down.  (2) is always possible, I plan to make a release with just some extra logging for you guys that will hopefully eliminate that as the problem.  (3) Is feeling pretty possible too, lately I've been getting a lot bugs in that points to problems in the latest supervisor release, 0.114.X ([example 1](https://github.com/sabeechen/hassio-google-drive-backup/issues/224), [example 2](https://github.com/sabeechen/hassio-google-drive-backup/issues/221)), but again that is pretty difficult to narrow down.

Other note, I've been unable to get the 32-bit arm version of Home assistant to run on my pi, so I'm going to buy a pi4 to see if I can repro this on that hardware (thanks patrons!).  It will be a few days before I can have the hardware delivered to test that out though.

**Comment by sabeechen** [comment]
The supervisor guy would like you to turn on crash reports, which you can get to from "Supervisor" > "System" > "Supervisor" panel > Toggle on "Share Diagnostics".  Hopefully this will get him something he can work with.

**Comment by davidsat** [comment]
HI Stephen,
I enabled diagnostic sharing. Do I need to do anything else?
Dave
p.s. Thanks for all the hard work you do, it's appreciated!

**Comment by sabeechen** [comment]
I'm not really sure, maybe he has some way to search for your error in their diagnostic reports?

**Comment by bortog** [comment]
me too, the same problem.


###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.1`
 Home Assistant Version: `0.114.2`
 Supervisor Version: `235`
 Architecture: `armv7`
 Date: `2020-08-20T16:05:29.446050+00:00`
 Timezone: `Europe/Rome`
 Failure Time: `2020-08-20T16:04:30.675310+00:00`
 Last Good Sync: `2020-08-20T16:04:28.569376+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:148 (save)
  addon/backup/drive/driverequests.py:244 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-08-19T22:03:24Z",
        "size": "4.2 GB"
    },
    "GoogleDrive": {
        "snapshots": 6,
        "retained": 2,
        "deletable": 4,
        "name": "GoogleDrive",
        "latest": "2020-08-16T22:03:23Z",
        "size": "8.0 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 08-20 16:26:41 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-20 16:26:41 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1h71VqMbHW-WX3BwOssiC45L1Kvecxu12/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-20 16:26:42 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271h71VqMbHW-WX3BwOssiC45L1Kvecxu12%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-20 16:26:42 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-08-20 00:03:23' to Google Drive
08-20 16:26:42 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-20 16:26:42 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AAANsUlKnMZipNMmOSH_7rNFj8sBoFZejUPDDRticURobOHKZPAcZG4OCdkteTobRrGDxxhVPzP3ixzBseYxDhp_GgMh8nfEGQ
08-20 16:26:42 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2755010560
08-20 16:26:42 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-20 16:26:42 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
08-20 17:09:22 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-20 17:09:22 INFO [backup.model.coordinator] Syncing Snapshots
08-20 17:09:22 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-20 17:09:22 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-20 17:09:23 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1h71VqMbHW-WX3BwOssiC45L1Kvecxu12/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-20 17:09:23 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271h71VqMbHW-WX3BwOssiC45L1Kvecxu12%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-20 17:09:23 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-08-20 00:03:23' to Google Drive
08-20 17:09:23 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-20 17:09:23 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=AAANsUlKnMZipNMmOSH_7rNFj8sBoFZejUPDDRticURobOHKZPAcZG4OCdkteTobRrGDxxhVPzP3ixzBseYxDhp_GgMh8nfEGQ
08-20 17:09:23 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2755010560
08-20 17:09:23 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-20 17:09:23 INFO [backup.model.coordinator] I'll try again in an hour
08-20 18:04:28 INFO [backup.model.coordinator] Syncing Snapshots
08-20 18:04:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-20 18:04:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1h71VqMbHW-WX3BwOssiC45L1Kvecxu12/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-20 18:04:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271h71VqMbHW-WX3BwOssiC45L1Kvecxu12%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-20 18:04:30 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-08-20 00:03:23' to Google Drive
08-20 18:04:30 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
08-20 18:04:30 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
08-20 18:04:30 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-20 18:04:30 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-08-20 14:37:21 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon[0m
[32m20-08-20 14:37:21 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance[0m
[32m20-08-20 14:37:21 INFO (MainThread) [supervisor.homeassistant] Successful run Home Assistant 0.114.3[0m
[32m20-08-20 14:37:21 INFO (SyncWorker_7) [supervisor.docker.interface] Cleanup images: ['homeassistant/raspberrypi4-homeassistant:0.114.2'][0m
[32m20-08-20 14:37:21 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m20-08-20 14:37:24 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m20-08-20 14:37:24 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m20-08-20 14:37:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m20-08-20 14:37:25 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m20-08-20 14:37:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m20-08-20 14:37:26 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m20-08-20 14:49:43 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json[0m
[32m20-08-20 14:51:44 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token[0m
[32m20-08-20 15:09:22 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-20 15:09:23 INFO (MainThread) [supervisor.api.security] /snapshots/ba235a71/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-20 15:09:23 INFO (MainThread) [supervisor.api.snapshots] Download snapshot ba235a71[0m
[32m20-08-20 15:21:50 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token[0m
[32m20-08-20 15:49:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/arthurdent75/SimpleScheduler repository[0m
[32m20-08-20 15:49:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository[0m
[32m20-08-20 15:49:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m20-08-20 15:49:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m20-08-20 15:49:46 INFO (MainThread) [supervisor.store] Load add-ons from store: 68 all - 0 new - 0 remove[0m
[32m20-08-20 15:51:54 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token[0m
[32m20-08-20 16:04:28 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-20 16:04:30 INFO (MainThread) [supervisor.api.security] /snapshots/ba235a71/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-20 16:04:30 INFO (MainThread) [supervisor.api.snapshots] Download snapshot ba235a71[0m
[32m20-08-20 16:04:44 INFO (MainThread) [supervisor.api.security] /snapshots/ba235a71/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-20 16:04:44 INFO (MainThread) [supervisor.api.snapshots] Download snapshot ba235a71[0m
[32m20-08-20 16:05:29 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 2020-08-20 18:04:00 INFO (MainThread) [homeassistant.components.automation.temporizzatore] Temporizzatore: Running script
2020-08-20 18:04:00 INFO (MainThread) [homeassistant.components.automation.temporizzatore] Temporizzatore: Executing step call service
2020-08-20 18:04:00 INFO (MainThread) [homeassistant.components.automation.aggiorna_termostati] aggiorna termostati: Running script
2020-08-20 18:04:00 INFO (MainThread) [homeassistant.components.automation.aggiorna_termostati] aggiorna termostati: Executing step call service
2020-08-20 18:04:00 INFO (SyncWorker_41) [homeassistant.components.python_script] Executing schedule.py: {}
2020-08-20 18:04:08 INFO (MainThread) [homeassistant.components.kodi.media_player] Unable to connect to Kodi via websocket
2020-08-20 18:04:09 ERROR (MainThread) [homeassistant.components.generic_thermostat.climate] Unable to update from sensor: could not convert string to float: 'None'
2020-08-20 18:04:16 WARNING (MainThread) [frontend.js.latest.202008110] Icon mdi:file-document-box-outline was renamed to mdi:text-box-outline, please change your config, it will be removed in version 0.115.
2020-08-20 18:04:16 WARNING (MainThread) [frontend.js.latest.202008110] Icon mdi:timer was renamed to mdi:timer-outline, please change your config, it will be removed in version 0.115.
2020-08-20 18:04:22 INFO (MainThread) [homeassistant.components.upnp] No UPnP/IGD devices discovered
2020-08-20 18:04:22 INFO (MainThread) [homeassistant.components.upnp] Unable to create UPnP/IGD, aborting
2020-08-20 18:04:22 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 80 seconds
2020-08-20 18:04:22 INFO (MainThread) [homeassistant.components.upnp] No UPnP/IGD devices discovered
2020-08-20 18:04:22 INFO (MainThread) [homeassistant.components.upnp] Unable to create UPnP/IGD, aborting
2020-08-20 18:04:22 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 80 seconds
2020-08-20 18:04:30 INFO (MainThread) [homeassistant.components.automation.aggiorna_termostati] Executing aggiorna termostati
2020-08-20 18:04:30 INFO (MainThread) [homeassistant.components.automation.aggiorna_termostati] aggiorna termostati: Running script
2020-08-20 18:04:30 INFO (MainThread) [homeassistant.components.automation.aggiorna_termostati] aggiorna termostati: Executing step call service
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.temporizzatore] Executing Temporizzatore
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.aggiorna_termostati] Executing aggiorna termostati
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.test2] Executing spegni riscaldamento
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.temporizzatore] Temporizzatore: Running script
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.temporizzatore] Temporizzatore: Executing step call service
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.aggiorna_termostati] aggiorna termostati: Running script
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.aggiorna_termostati] aggiorna termostati: Executing step call service
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.test2] spegni riscaldamento: Running script
2020-08-20 18:05:00 INFO (MainThread) [homeassistant.components.automation.test2] spegni riscaldamento: Executing step device automation
2020-08-20 18:05:00 INFO (SyncWorker_8) [homeassistant.components.python_script] Executing schedule.py: {}
2020-08-20 18:05:09 ERROR (MainThread) [homeassistant.components.generic_thermostat.climate] Unable to update from sensor: could not convert string to float: 'None'

 ```

**Comment by sabeechen** [comment]
I've tried to reproduce this on a number of platforms and configurations (pi2 32 bit, pi3 64 bit, pi4 64 bit, 64 bit ubuntu) but haven't been able to get it to have any problems with the supervisor.  I'll need some more help from you guys to figure this out.

I've released a new version of the addon (0.101.2) thats capable of providing a lot more logging output that might help figure out whats wrong.  Could I have you guys do the following:
- Make sure you're using the latest version of the supervisor and update if necessary
- Update the addon to 0.101.2
- Add the following to your addon config:
  - `log_level: 'TRACE'`
  - `console_log_level': 'TRACE'`
  This will make the addon produce an obscene amount of logs, and burried in there is hopefully the info I need.  These options cant be set using the web-ui.
- Restart the addon and verify that the error comes up when ti attempts to sync.
- Go the the "LOGS" page via the add-on web UI
- At the top will be a link to download the logs.  Click it and save them somewhere.
- Attach the logs here or email them to me stephen@beechens.com if you're worried about leaking personal information.  I've taken some care to ensure no sensitive info gets printed, but I can't be certain.

**Comment by Chimerique** [comment]
Just tried it out, last update seems to be fixing the isue 


In any case thx for the addon, it's very usefull!

**Comment by davidsat** [comment]
Hi Stephen,
Here is my log with debug enabled. New version did not help.

**Comment by bortog** [comment]
Hello Stephen,

this is my log, still the same problem but it happened the last snapshot has been uploaded to drive even if the red message with the error is still there.

Thanks
[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/5140778/home-assistant-google-drive-backup.log)

**Comment by gbutters** [comment]
Still not working

On August 24, 2020, at 3:24 PM, Stephen Beechen <notifications@github.com> wrote:

I've tried to reproduce this on a number of platforms and configurations (pi2 32 bit, pi3 64 bit, pi4 64 bit, 64 bit ubuntu) but haven't been able to get it to have any problems with the supervisor. I'll need some more help from you guys to figure this out.

I've released a new version of the addon (0.101.2) thats capable of providing a lot more logging output that might help figure out whats wrong. Could I have you guys do the following:

Make sure you're using the latest version of the supervisor and update if necessary

Update the addon to 0.101.2

Add the following to your addon config: 

log_level: 'TRACE'

console_log_level': 'TRACE'
This will make the addon produce an obscene amount of logs, and burried in there is hopefully the info I need. These options cant be set using the web-ui.

Restart the addon and verify that the error comes up when ti attempts to sync.

Go the the "LOGS" page via the add-on web UI

At the top will be a link to download the logs. Click it and save them somewhere.

Attach the logs here or email them to me stephen@beechens.com if you're worried about leaking personal information. I've taken some care to ensure no sensitive info gets printed, but I can't be certain.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/sabeechen/hassio-google-drive-backup/issues/226#issuecomment-679346730", "url": "https://github.com/sabeechen/hassio-google-drive-backup/issues/226#issuecomment-679346730", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by gbutters** [comment]
[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/5146117/home-assistant-google-drive-backup.log)

**Comment by FaserF** [comment]
same issue for me. 
More issues with the same problem: #250  #243

**Comment by sabeechen** [comment]
Its still a problem, so far I have no idea.

From the logs what it looks like is happening is that the addon requests to download a snapshot from the supervisor, the supervisor responds with HTTP 200 (success) and indicates it has a large payload (eg the snapshot bytes), but then closes the connection right away without sending anything else.  The addon attempts to read the full response, which fails because the connection is closed, then starts over and runs into the same problem over and over.  I need to figure out why the supervisor isn't actually sending its bytes back.

So far I've been unable to reproduce this on any of my test instances, which has made diagnosing it difficult.

**Comment by turbatus** [comment]
To reproduce this issue did you used the Supervised Homeassistant installation?
I am on this installation type and having this issue.

**Comment by sabeechen** [comment]
I haven't, just the pre-built images.  What platform are you running the supervised installation on (eg hardware, os, etc)?

**Comment by turbatus** [comment]
RPi4 with 4Gb RAM, Raspbian GNU/Linux 10. Home Assistant is the latest version (upgraded when prompted), installation method is this one: https://github.com/home-assistant/supervised-installer

**Comment by davidsat** [comment]
Hi,
I'm not using the supervised version. I'm using HassOs.
Dave

**Comment by matteobombardi** [comment]
same here

**Comment by sabeechen** [comment]
I tried to reproduce this again, using the supervised installer, but with no success.  Here is the setup method I used:
- Hardware: Raspberry pi 4 8GB model
- Flashed Raspberry Pi OS (32-bit) Using Raspberry Pi Imager v1.2
- Ran these commands based on the supervised installation docs (and a bunch of resources to install dependencies):
  ```bash
  sudo apt-get update
  sudo apt-get upgrade

  # Install dependencies
  curl -fsSL https://get.docker.com -o get-docker.sh
  sudo sh get-docker.sh
  sudo usermod -aG docker pi
  sudo apt-get install jq
  sudo apt-get install network-manager
  sudo apt install apparmor-profiles
  sudo systemctl enable apparmor.service
  sudo systemctl start apparmor.service

  # Install HA/Supervisor
  sudo curl -sL https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh | sudo bash -s -- -m raspberrypi4
  ```
- Install the addon, take a snapshot, backup, etc

I still didn't run into any problems with the addon.  Supervised installation on raspbian isn't officially supported, maybe you have a dependency out of date?

**Comment by Game2Freak** [comment]
I’m on HassOS and still experiencing the sync issue.

**Comment by turbatus** [comment]
Another thing: In the add-on page it says that I have 4 snapshots in HA. I tried to download the most recent 2 snapshots (1 day old and 3 days old) and the downloaded file has 1 KB (whilst the snapshot size is reported to be 3.3 Gb). I don't know if is related to this issue.
![image](https://user-images.githubusercontent.com/8330709/92004378-7385e280-ed42-11ea-9c0a-8ba244e19aca.png)

**Comment by sabeechen** [comment]
The small download is caused by the same problem.  When you donwload a snapshot through the addon, the addon actually donwloads the snapshot from the supervisor first which starts fine but then errors out.  You should still be able to download snapshots by going to `Supervisor` > `Snapshots` in the Home Assistant UI.

**Comment by FaserF** [comment]
For me it is working again with the latest OS release 4.13

**Comment by davidsat** [comment]
Just updated to 4.13, problem is still there.
Dave

**Comment by bortog** [comment]
Unfortunately, not working even after 4.13 update.

I noticed I have some snapshot uploaded on gdrive and they are "small" (less than 1 Gb). Bigger snapshot are not uploaded.

![image](https://user-images.githubusercontent.com/62393717/92747997-021ee300-f385-11ea-8a46-ec780068205c.png)

**Comment by sabeechen** [comment]
That sit, size appears to be the issue.  I'm able to reliably reproduce this with snapshots over 2GB with a raspberry pi2.  Moreover I'm unable to download these large snapshots through the supervisor web-ui, which means this is definitely a problem with the supervisor.
I've [opened a bug](https://github.com/home-assistant/supervisor/issues/2047) with the supervisor and summarized everything I've learned about this so far.  If I don't hear back from the devs soon, I'll start trying to figure it out myself but for now they're in a much better position to figure this out.

**Comment by roblamoreaux** [comment]
I just got this after adding files to the new media browser folder. 
Since I have those files elsewhere I don't care if they get backed up and I don't want to waste the space backing them up every day.
So can you add a configuration setting to have the snapshot to ignore the media folder since it is not in the partial dialog now?

**Comment by sabeechen** [comment]
I'll be adding it in the next release.

**Comment by Game2Freak** [comment]
Hello,

Thanks for your efforts towards this issue.

Are there any updates from the supervisor devs?

**Comment by sabeechen** [comment]
Nothing yet, though I did get someone to take a look.   I think this problem may actually come from an external library that the supervisor depends on.   Seems like they've got bigger fish to fry but I'll keep poking.

In the mean time here is everything you can do (AFAIK) to mitigate this problem:
- Install the 64 bit version of Home Assistant instead.  I have yet to find a downside to doing this, I'm not sure why the 32 bit versions are recommended on a native 64 bit platform.
-  Make the snapshots smaller.  Some testing I've done indicates that just under 2GB is the magic limit where this breaks.  There are a number of ways to do this, but most helpfully is to (1) lower [purge_keep_days](https://www.home-assistant.io/integrations/recorder/#purge_keep_days) as far as you can and (2) Use partial snapshots exclude addons and folders you don't strictly need.

Neither of these are really a solution, but they will work for some.

**Comment by sabeechen** [comment]
Ah looks like this morning they pinned it down to a bug in python, which they've patched for a future release of the supervisor.  I'm not sure how fast their release cycle is, but a fix is in the works.

**Comment by sabeechen** [comment]
It looks like the latest released version of the supervisor (2020.11.0) fixes this issue but if anyone is still having problems after updating, please let me know.

**Comment by davidsat** [comment]
Hi,
2020.11.0 fixed it for me.
Thanks!
