### ISSUE TITLE
Add-on is not running. Please start it first

### ISSUE THREAD

**Issue by spencerthayer** [sabeechen/hassio-google-drive-backup#710]
```
Home Assistant Google Drive Backup
Add-on is not running. Please start it first
```

When I go to start the add-on it doesn''t do anything. Just hangs. I uninstalled it and re-installed it and the error persists. Any ideas?

This is the log

```
09-05 23:20:16 INFO Starting server on port 8099
09-05 23:20:16 INFO Server started
09-05 23:20:16 INFO Syncing Backups
```

**Comment by sabeechen** [comment]
The logs indicate the addon is running.  The addon can't produce log output otherwise, though perhaps it stopped without any error output?

I've had a number of people report this issue, but when I ask them to go back and investigate it has resolved itself and it doesn't seem to come back.  I suspect something is wrong with Home Assistant and not the addon.  Hopefully you will be able to catch the problem in the act.  I have little patience for ghosts.

Could I have you:
- Go to your user profile page in Home Assistant and turn on "Advanced Mode", this will let you see the supervisor's logs.
- Go to the addon installaiton page.
- Click "Start" and verify that you still see the problem.
- Refresh the Home Assistant web-ui (a hard refresh, CTRL + F5), and verify you still see the problem.  Sometimes HA caches state improperly.
- Go to <kbd>Settings</kbd> > <kbd>System</kbd> > <kbd>Logs</kbd> > <kbd>Supervisor (top right drop down)</kbd>
- See if any errors show up there.

**Comment by redsilver** [comment]
I have the same problem. I followed all the steps above but it still tell me that "Add-on is not running. Please start it first".
The supervisor's logs it says: "22-09-19 10:17:37 WARNING (MainThread) [supervisor.addons.addon] cebe7a76_hassio_google_drive_backup is already running!". I tried to unistall/reinstall the add-on without success. 
After reinstalling, it doesn't let me log in again.

Versions:
Home Assistant 2022.9.5
Supervisor 2022.09.dev1703
Frontend 20220907.2 - latest

**Comment by safounder** [comment]
Same issue here. Is there any workaround?
It is first time I install this add-on, I can't really connect to Google Drive auth without web ui working.

> I have the same problem. I followed all the steps above but it still tell me that "Add-on is not running. Please start it first". The supervisor's logs it says: "22-09-19 10:17:37 WARNING (MainThread) [supervisor.addons.addon] cebe7a76_hassio_google_drive_backup is already running!". I tried to unistall/reinstall the add-on without success. After reinstalling, it doesn't let me log in again.
> 
> Versions: Home Assistant 2022.9.5 Supervisor 2022.09.dev1703 Frontend 20220907.2 - latest

**Comment by safounder** [comment]
Ok, got it fixed by reboot hardware (Raspberry Pi).

**Comment by BlueBackbite** [comment]
Same issue, however, EVERY add-on is not starting.
I've been having problems with SD cards (possibly ???) where if the default gateway goes down, all of home assistant dies.
So I restored from backup, updated core to latest.

Addons are showing as running, but HA UI cannot see that they are running.
Doing more research here, maybe I can post more information if I find it.

All of this is on an RPI4 4GB.

**Comment by sabeechen** [comment]
Its looking more clear to me that this is some kind of problem with Home Assistant's supervisor, since a system reboot (which afaik is the only way to reboot the supervisor) always fixes it.

I'm closing this issue since there isn't anything else I can do from my side, but please feel free to reopen this is you think I can help.

**Comment by bertarends** [comment]
I had the same problem. A restart of HA from the UI didn't solve the problem. A restrart from the supervisor with a terminal session (using the terminal/ssh add-on) and the command 'ha supervisor restart' solved the problem.
